name: 'Pull Request Labeler'
description: 'Label your Prs with your issues types'
author: 'SteveG-tkorp'
inputs: 
  GITHUB_TOKEN:
    description: 'The GITHUB_TOKEN secret'
  pr_number:
    description: "The PR number"
    # required: true
  issue_number:
    description: "The issue number"
    # required: true
outputs:
  pr_updated:
    description: "The PR slightly updated to test this action"
runs:
  using: 'node20'
  main: 'lib/main.js'