name: 'Pull Request Labeler'
description: 'Label your Prs with your issues types'
author: 'SteveG-tkorp'
inputs: 
  GITHUB_TOKEN:
    description: 'The GITHUB_TOKEN secret'
  CONFIG_PATH:
    description: 'The path for the config file (root)'
runs:
  using: 'node12'
  main: 'lib/main.js'